#!/bin/sh
cat<<'REALEOF'
cat >candle<<EOF
#!/bin/sh
exec docker run -it --rm -e WD=\`pwd\` -h \`hostname\` -v /:\`pwd\` felfert/wix \`basename \$0\` "\$@"
EOF
chmod +x candle
REALEOF
cat<<REALEOF
for f in `cat /usr/local/etc/wixbins.lst` ; do
    ln -s candle \$f
done
REALEOF
