#!/bin/sh
cat<<'REALEOF'
cat >candle<<EOF
#!/bin/sh
EVARS=
for ev in \`env | grep ^WIX_|cut -d= -f1\` ; do
    EVARS="\$EVARS -e \$ev"
done
SECOPT=
if docker run --help | grep -q -- --security-opt ; then
    SECOPT="--security-opt label:disable"
fi
exec docker run \$SECOPT -i --rm -e WD=\`pwd\` \$EVARS -h \`hostname\` -v /:/work docker.echo360.net/wix \`basename \$0\` "\$@"
EOF
chmod +x candle
REALEOF
cat<<REALEOF
for f in `cat /usr/local/etc/wixbins.lst` ; do
    ln -s candle \$f
done
REALEOF
