name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'LICENSE'
      - '**/*.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'LICENSE'
      - '**/*.md'
      - '.github/**/*'
  workflow_dispatch:
  workflow_call:
    inputs:
      reason:
        required: true
        type: string

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set timestamp
      run:  echo "STAMP=$(date +%s)" >> $GITHUB_ENV 
    - name: Build docker image (debian)
      run:  docker build . --platform linux/386 --file Dockerfile --tag felfert/wix:${STAMP}
    - name: Build docker image (alpine)
      run:  docker build . --platform linux/386 --file Dockerfile-slim --tag felfert/wix:${STAMP}-slim
    - name: Save images
      run:  |
          docker save -o ${STAMP}.tar felfert/wix:${STAMP}
          docker save -o ${STAMP}-slim.tar felfert/wix:${STAMP}-slim
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: docker-wix
        if-no-files-found: error
        path: '*.tar'
        compression-level: 0
        retention-days: 1

  scan:
    name: Scan images
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Scan image (debian)
      id: scan-debian
      uses: anchore/scan-action@v6
      with:
        fail-build: false
        image: "felfert/wix:${STAMP}"

  report:
    # disabled for now (scan produces invalid sarif)
    if: ${{ false }}
    name: Upload scan reports
    needs: [scan]
    runs-on: ubuntu-latest
    steps:
    - name: Upload scan report (debian)
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan-debian.outputs.sarif }}
    - name: Scan image (alpine)
      id: scan-alpine
      uses: anchore/scan-action@v6
      with:
        fail-build: false
        image: "felfert/wix:${STAMP}-slim"
    - name: Upload scan report (alpine)
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan-alpine.outputs.sarif }}
    - name: Save images
      run:  |
          docker save -o ${STAMP}.tar felfert/wix:${STAMP}
          docker save -o ${STAMP}-slim.tar felfert/wix:${STAMP}-slim

  deploy:
    if: ( github.event_name == 'push' && github.ref_type == 'tag' ) || inputs.reason == 'upstream-change'
    needs: [build]
    name: Call
    uses: ./.github/workflows/CD.yml
    secrets: inherit
    with:
      caller-id: ${{ github.run_id }}
