name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'LICENSE'
      - '**/*.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'LICENSE'
      - '**/*.md'
      - '.github/**/*'
  workflow_dispatch:
  workflow_call:
    inputs:
      reason:
        required: true
        type: string

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set timestamp
      run: echo "STAMP=$(date +%s)" >> $GITHUB_ENV
    - name: Build docker image (debian)
      run:  docker build . --platform linux/386 --file Dockerfile --tag felfert/wix:${STAMP}
    - name: Build docker image (alpine)
      run:  docker build . --platform linux/386 --file Dockerfile-slim --tag felfert/wix:${STAMP}-slim
    - name: Save images
      run: |
          docker save -o ${STAMP}.tar felfert/wix:${STAMP}
          docker save -o ${STAMP}-slim.tar felfert/wix:${STAMP}-slim
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      id: artifact-upload-step
      with:
        name: docker-wix
        if-no-files-found: error
        path: '*.tar'
        compression-level: 0
        retention-days: 1

  scan:
    name: Scan images
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Fetch artifacts
      uses: actions/download-artifact@v8
      with:
        github-token: "${{ secrets.ARTIFACT_READ }}"
        name: docker-wix
    - name: Set STAMP
      run: echo STAMP="$(echo [0-9]*-*.tar | sed s/-.*//)" >> $GITHUB_ENV
    - name: Load images
      run: |
          for t in *.tar ; do
            docker load -i $t
          done
    - name: Scan image (debian)
      id: scan-debian
      uses: anchore/scan-action@v7
      with:
        fail-build: false
        cache-db: true
        image: "felfert/wix:${{env.STAMP}}"
    - name: Upload scan report (debian)
      uses: github/codeql-action/upload-sarif@v4
      with:
        category: "Image based on debian"
        sarif_file: ${{ steps.scan-debian.outputs.sarif }}
    - name: Scan image (alpine)
      id: scan-alpine
      uses: anchore/scan-action@v7
      with:
        fail-build: false
        cache-db: true
        image: "felfert/wix:${{env.STAMP}}-slim"
    - name: Upload scan report (alpine)
      uses: github/codeql-action/upload-sarif@v4
      with:
        category: "Image based on alpine"
        sarif_file: ${{ steps.scan-alpine.outputs.sarif }}

  deploy:
    if: ( github.event_name == 'push' && github.ref_type == 'tag' ) || inputs.reason == 'upstream-change'
    needs: [build]
    name: Call
    uses: ./.github/workflows/CD.yml
    secrets: inherit
    with:
      caller-id: ${{ github.run_id }}
