name: Publish README

on:
  push:
    branches: [ "master" ]
    paths:
      - README.md
      - .github/workflows/README.yml
  workflow_dispatch:

jobs:
  deploy:
    name: Update Push README.md to Docker hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_UPDATE_README }}
        repository: felfert/wix
