name: Check dependencies

on:
  workflow_dispatch:
#  schedule:
#    - cron: "23 5 * * *"

jobs:

  check:
    name: Check base images
    runs-on: ubuntu-latest
    outputs:
      needrebuild: ${{ steps.debian.outputs.needs-updating || steps.alpine.outputs.needs-updating }}
    steps:
      - uses: actions/checkout@v7
      - name: Check i386/debian:stable-slim
        id: debian
        uses: lucacome/docker-image-update-checker@v3.1.1
        with:
          base-image: debian:stable-slim
          image: felfert/wix:latest
          platforms: linux/386
      - name: Check i386/alpine
        id: alpine
        uses: lucacome/docker-image-update-checker@v3.1.1
        with:
          base-image: alpine
          image: felfert/wix:latest-slim
          platforms: linux/386
      - Print
        run: echo "${{ steps.debian.outputs.needs-updating }} ${{ steps.alpine.outputs.needs-updating }}"

  rebuild:
    if: ${{ false }} # debugging
    #if: ${{ needs.check.outputs.needrebuild }}
    needs: [check]
    name: Call
    uses: ./.github/workflows/CI.yml
    secrets: inherit
    with:
      reason: 'upstream-change'
